# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8774b84f695a3b09988b1aca3d6ee057ecb1eb0e22acf04906e06b3729e80bfcdfa639c353074cf9cfd9a176817d84669074c8784373924dde9aa120eb8df6c4

test:
  secret_key_base: 11813cc147679cc70cf2720f56d6770fe5d419e6d4bf5a9035cd039644eb696d9817db8aea34a12b96c3789f1a2930cd93d5f2f28f9568791f5c6ce0ffaeb0b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
